name: Gitbook action
on: workflow_dispatch #push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@master
      with:
        source_branch: main
        source_dir: docs
        token: ${{ secrets.GITHUB_TOKEN }}
